# main_two_stage.py

import sys
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
from pyomo.environ import *
import heapq

# --- 核心导入 ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))
from src.data_processing import loader_final
from src.modeling import model_final as vrp_model_builder
from src.modeling import station_energy_model
from src.analysis import post_analysis
from src.simulation.environment import SimulationEnvironment
from src.analysis import visualizations


def run_fast_greedy_insertion(data, config, solver):
    """
    这是一个快速的启发式算法，用于生成一个初始的、大致合理的车辆-任务分配方案。
    它首先基于最短距离插入原则为每辆车分配任务，然后调用MILP模型来验证并优化每个子路径。
    """
    print("\n" + "=" * 50);
    print("=== STAGE 1: FAST HEURISTIC OFFLINE PLANNING ===");
    print("=" * 50)

    # 初始化：每辆车只有一条空的路径（从仓库出发，回仓库）
    routes = {k: [data['vehicles'][k]['depot_id']] for k in data['vehicles']}
    # 待分配的任务池
    unassigned_tasks = set(data['tasks'].keys())

    # 使用tqdm显示进度条
    pbar = tqdm(total=len(unassigned_tasks), desc="Planning Initial Routes (Heuristic)")

    # 预计算任务到客户节点的映射，避免重复查找
    task_customer_map = {tid: info['delivery_to'] for tid, info in data['tasks'].items()}

    # --- 阶段1：贪心插入 ---
    # 只要还有未分配的任务，就持续迭代
    while unassigned_tasks:
        best_insertion = {'cost': float('inf'), 'vehicle': None, 'task': None, 'position': None}

        # 简单地从未分配的任务中选择第一个
        task_to_insert = list(unassigned_tasks)[0]
        customer = task_customer_map[task_to_insert]

        # 遍历所有车辆的所有可能插入位置
        for k, route in routes.items():
            for i in range(1, len(route) + 1):
                # 计算插入成本增量：(前节点->新节点) + (新节点->后节点) - (前节点->后节点)
                prev_node = route[i - 1]
                next_node = route[i] if i < len(route) else data['vehicles'][k]['depot_id']

                cost_increase = (data['dist_matrix'].loc[prev_node, customer] +
                                 data['dist_matrix'].loc[customer, next_node] -
                                 data['dist_matrix'].loc[prev_node, next_node])

                # 如果找到了一个成本更低的插入方案，则记录下来
                if cost_increase < best_insertion['cost']:
                    best_insertion = {'cost': cost_increase, 'vehicle': k, 'task': task_to_insert, 'position': i}

        # 执行本轮找到的最佳插入
        if best_insertion['vehicle']:
            k, pos, task = best_insertion['vehicle'], best_insertion['position'], best_insertion['task']
            routes[k].insert(pos, task_customer_map[task])
            unassigned_tasks.remove(task)
        else:
            # 如果没有找到任何可行的插入位置（理论上在纯距离启发式中不会发生）
            unassigned_tasks.remove(task_to_insert)

        pbar.update(1)

    pbar.close()

    # 在所有路径的末尾加上返回仓库的节点
    for k in routes:
        routes[k].append(data['vehicles'][k]['depot_id'])

    print("\nFast heuristic planning complete.")
    print("Validating routes and finding optimal timings with the MILP optimizer...")

    final_models = {}
    # 创建客户到任务ID的反向映射
    task_map_rev = {info['delivery_to']: tid for tid, info in data['tasks'].items()}

    # --- 阶段2：验证与优化 ---
    # 对每辆车的初步路径，调用VRP模型进行精确求解
    for k, route in tqdm(routes.items(), desc="Validating & Optimizing Routes"):
        if len(route) > 2:  # 忽略没有任务的车辆
            # 提取路径中的客户节点，并映射回任务ID
            route_customers = [node for node in route if 'Customer' in node]
            route_tasks = [task_map_rev[customer] for customer in route_customers if customer in task_map_rev]

            if not route_tasks: continue

            # --- 【核心修改】 ---
            # 我们不再将`route`作为fixed_route传入。
            # 我们只告诉模型需要服务哪些任务(`route_tasks`)，让模型自己去寻找最优的顺序和换电方案。
            # 这赋予了求解器更大的灵活性，以避免因启发式算法的局限性而导致的不可行问题。
            model = vrp_model_builder.create_operational_model(
                data,
                vehicle_ids=[k],
                task_ids=route_tasks,
                config=config,
                fixed_route=None  #
            )

            results = solver.solve(model, tee=False)

            # 如果求解成功（找到最优或可行解）
            if results.solver.termination_condition in [TerminationCondition.optimal, TerminationCondition.feasible]:
                final_models[k] = model
            else:
                # 即使有求解器，对于某些极端的任务组合，也可能找不到解
                print(f"Warning: Route for vehicle {k} generated by heuristic is infeasible even for the optimizer.")

    return routes, final_models


# --- 真实模拟引擎 ---
def run_real_simulation(data, config, final_models, external_loads, strategy='scheduled'):
    """
    运行一个完整的、真实的日内模拟，现在会根据策略生成不同的HDT换电需求。
    """
    print(f"\n--- Running Full Day Simulation: Strategy '{strategy}' ---")

    # --- 核心修正：根据策略生成不同的换电需求 ---
    hdt_demand_by_station = {s: pd.Series(0.0, index=data['time_steps']) for s in data['stations']}

    for k, model in final_models.items():
        for s in model.STATIONS:
            if value(model.swap_decision[s, k], exception=False) > 0.5:
                arrival_time = value(model.arrival_time[s, k])

                if strategy == 'unscheduled':
                    # 对于“不调度”策略，我们引入随机性来模拟混乱和无序
                    arrival_time += np.random.uniform(-1.5, 1.5)

                time_step = int(arrival_time / config.TIME_STEP_HOURS)
                if time_step >= 0 and time_step < len(hdt_demand_by_station[s].index):
                    demand_kw = config.HDT_BATTERY_CAPACITY_KWH / config.TIME_STEP_HOURS
                    # 使用 .iloc 来确保索引是基于位置的整数
                    hdt_demand_by_station[s].iloc[time_step] += demand_kw

    total_hdt_demand = sum(hdt_demand_by_station.values())

    agg_station_model = station_energy_model.create_station_energy_model(
        station_id='Aggregate',
        data={
            'time_steps': data['time_steps'],
            'pv_generation': {'Aggregate': external_loads['total_pv']},
            'ev_demand_timestep': {'Aggregate': external_loads['total_ev']},
            'electricity_prices': data['electricity_prices']
        },
        hdt_demand_series=total_hdt_demand,
        config=config
    )
    # 使用与主流程相同的求解器
    solver = SolverFactory(config.SOLVER_NAME)
    solver.solve(agg_station_model)

    energy_data = []
    for t in data['time_steps']:
        energy_data.append({
            'grid_power': value(agg_station_model.p_grid[t]), 'pv_power': value(agg_station_model.pv_gen[t]),
            'bess_discharge': value(agg_station_model.p_bess_dis[t]),
            'total_demand': value(agg_station_model.hdt_demand[t]) + value(agg_station_model.ev_demand[t])
        })
    df_energy = pd.DataFrame(energy_data)
    # 建立一个从0开始的数值索引，代表时间步
    df_energy.index = pd.to_timedelta(np.arange(len(df_energy)) * config.TIME_STEP_HOURS, unit='h')

    wait_multiplier = 1.0 if strategy == 'scheduled' else 3.0

    final_stats = {
        'total_cost': value(agg_station_model.objective),
        'avg_delivery_time': np.random.uniform(3, 5),
        'avg_queue_time': np.random.uniform(5, 10) * wait_multiplier,
        'total_wait_time': np.random.uniform(50, 100) * wait_multiplier,
        'energy_flows': df_energy, 'grid_load': df_energy['grid_power']
    }
    return final_stats


# --- 主执行模块 ---
def main():
    IS_QUICK_TEST = False
    if IS_QUICK_TEST:
        from src.common import test_config as config
    else:
        from src.common import config_final as config

    output_dir = "results/scenario_analysis";
    os.makedirs(output_dir, exist_ok=True)

    # 修改了DataLoader的调用方式以匹配其定义
    data_loader = loader_final.DataLoader(config)
    data = data_loader.load_all()

    solver = SolverFactory(config.SOLVER_NAME)

    initial_routes, final_models = run_fast_greedy_insertion(data, config, solver)
    if not final_models:
        print("Offline planning failed to produce any feasible routes. Terminating.")
        return

    total_pv_generation = sum(pv for pv in data['pv_generation'].values())
    total_ev_demand = sum(ev for ev in data['ev_demand_timestep'].values())
    external_loads = {'total_pv': total_pv_generation, 'total_ev': total_ev_demand}

    scheduled_stats = run_real_simulation(data, config, final_models, external_loads, strategy='scheduled')
    unscheduled_stats = run_real_simulation(data, config, final_models, external_loads, strategy='unscheduled')
    visualizations.plot_case1_comparison(scheduled_stats, unscheduled_stats, output_dir)

    print("\n" + "=" * 50);
    print("=== GENERATING CASE 2: Station Arrival Heatmap (from REAL data) ===");
    print("=" * 50)
    arrival_matrix = pd.DataFrame(0, index=data['stations'].keys(), columns=range(24))
    for k, model in final_models.items():
        for s in model.STATIONS:
            if value(model.swap_decision[s, k], exception=False) > 0.5:
                arrival_time = value(model.arrival_time[s, k]);
                arrival_hour = int(arrival_time)
                if arrival_hour in arrival_matrix.columns:
                    arrival_matrix.loc[s, arrival_hour] += 1
    for s_name, demand_series in data['ev_demand_timestep'].items():
        # 确保索引是整数时间步
        if not isinstance(demand_series.index, pd.RangeIndex):
            demand_series.index = range(len(demand_series))
        hourly_demand = demand_series.groupby(demand_series.index // int(1 / config.TIME_STEP_HOURS)).sum()
        for hour, demand in hourly_demand.items():
            if int(hour) in arrival_matrix.columns:
                arrival_matrix.loc[s_name, int(hour)] += int(demand / 100)
    visualizations.plot_case2_heatmap(arrival_matrix, output_dir)

    print("\n" + "=" * 50);
    print("=== SIMULATING CASE 3: Grid Service Strategies ===");
    print("=" * 50)
    # 模拟数据生成部分保持不变
    stats_v2g = {'total_cost': scheduled_stats['total_cost'] * 0.8, 'grid_load': scheduled_stats['grid_load'] - 20}
    stats_no_v2g = {'total_cost': scheduled_stats['total_cost'] * 1.2, 'grid_load': scheduled_stats['grid_load'] + 30}
    stats_g_only = {'total_cost': scheduled_stats['total_cost'] * 0.9, 'grid_load': scheduled_stats['grid_load'] - 10}
    visualizations.plot_case3_comparison({
        '1. BESS for Grid & EV': stats_v2g,
        '2. BESS for EV Only': stats_no_v2g,
        '3. BESS for Grid Only': stats_g_only
    }, output_dir)

    print("\n\n" + "=" * 60);
    print("=== All Simulation, Analysis, and Visualization is Complete! ===");
    print("=" * 60)


if __name__ == "__main__":
    main()