# src/common/test_config.py
# (这是一个新文件)

import os

# --- [测试场景] ---
# 大幅度减小规模以进行快速测试
CITY_NODE_COUNT = 50
CITY_GRAPH_RADIUS = 0.3
NUM_DEPOTS = 1
NUM_TRUCKS = 4         # 大幅减少车辆数
NUM_STATIONS = 3
NUM_CUSTOMERS = 8      # 大幅减少客户数
MIN_TASKS_PER_TRUCK = 1
MAX_TASKS_PER_TRUCK = 3  # 减少最大任务数
CITY_SCALE_KM = 40.0

# --- 时间离散化 ---
TIME_HORIZON_HOURS = 24
TIME_STEP_MINUTES = 30
TOTAL_TIME_STEPS = int(TIME_HORIZON_HOURS * 60 / TIME_STEP_MINUTES)
TIME_STEP_HOURS = TIME_STEP_MINUTES / 60.0

# --- 经济与惩罚参数 ---
MANPOWER_COST_PER_HOUR = 150.0
DELAY_PENALTY_PER_HOUR = 800.0
FIXED_SWAP_COST = 50.0
EV_UNSERVED_PENALTY_PER_KWH = 10.0
GRID_PEAK_PRICE_PENALTY = 50.0
UNASSIGNED_TASK_PENALTY = 2000000.0
AVG_TASKS_PER_TRUCK = (MIN_TASKS_PER_TRUCK + MAX_TASKS_PER_TRUCK) / 2
MAX_WORKING_HOURS_PER_TRUCK = 12.0

# --- HDT 物理参数 (使用健壮的参数) ---
LOADING_UNLOADING_TIME_HOURS = 0.5
SWAP_DURATION_HOURS = 0.25
HDT_BATTERY_CAPACITY_KWH = 350.0
HDT_MIN_SOC_KWH = HDT_BATTERY_CAPACITY_KWH * 0.20
HDT_EMPTY_WEIGHT_TON = 10.0
HDT_BASE_CONSUMPTION_KWH_PER_KM = 1.2
HDT_WEIGHT_CONSUMPTION_KWH_PER_KM_TON = 0.05

# --- EV & 能源站参数 ---
STATION_BESS_CAPACITY_KWH = 1000.0
STATION_BESS_MAX_POWER_KW = 250.0
STATION_BESS_EFFICIENCY = 0.93
STATION_MAX_GRID_POWER_KW = 2000
PV_PEAK_POWER_KW = 500
PV_CLOUD_NOISE_LEVEL = 0.4
EV_DEMAND_PEAK_KW = 200
EV_DEMAND_NOISE_LEVEL = 0.2

# --- 求解器与模型 ---
SOLVER_NAME = 'gurobi'
TIME_LIMIT_SECONDS = 600
BIG_M = 10000