# src/common/test_config.py

# --- 核心模拟参数 ---
IS_QUICK_TEST = True
TOTAL_TIME_STEPS = 24
TIME_STEP_HOURS = 1
TIME_HORIZON_HOURS = 24

# --- 求解器配置 (MODIFIED) ---
SOLVER_NAME = 'gurobi'  # 快速测试同样使用gurobi
SOLVER_THREADS = 4

# --- 路网和场景生成 ---
CITY_NODE_COUNT = 30
CITY_GRAPH_RADIUS = 0.5
CITY_SCALE_KM = 20.0
NUM_DEPOTS = 1
NUM_STATIONS = 3
NUM_CUSTOMERS = 5
NUM_TRUCKS = 2
MIN_TASKS_PER_TRUCK = 1
MAX_TASKS_PER_TRUCK = 3

# --- 车辆参数 ---
HDT_BATTERY_CAPACITY_KWH = 282.0
HDT_MIN_SOC_KWH = HDT_BATTERY_CAPACITY_KWH * 0.2
HDT_EMPTY_WEIGHT_TON = 10.0
HDT_BASE_CONSUMPTION_KWH_PER_KM = 0.8
HDT_WEIGHT_CONSUMPTION_KWH_PER_KM_TON = 0.05
LOADING_UNLOADING_TIME_HOURS = 0.5
SWAP_DURATION_HOURS = 0.25

# --- 成本和惩罚 ---
MANPOWER_COST_PER_HOUR = 80.0
FIXED_SWAP_COST = 50.0
DELAY_PENALTY_PER_HOUR = 200.0
UNASSIGNED_TASK_PENALTY = 10000.0
GRID_ELECTRICITY_COST_YUAN_PER_KWH = 1.2

# --- 换电站能源参数 ---
BESS_CAPACITY_KWH = 1000.0
BESS_MAX_POWER_KW = 250.0
BESS_EFFICIENCY = 0.95
PV_PEAK_POWER_KW = 200.0
PV_CLOUD_NOISE_LEVEL = 0.4
EV_DEMAND_PEAK_KW = 300.0
EV_DEMAND_NOISE_LEVEL = 0.2

# --- 动态警报与重规划参数 ---
STATION_QUEUE_ALARM_THRESHOLD = 2
GRID_BUS_ALARM_MW = 5.0
TRAFFIC_JAM_PROBABILITY = 0.1

# --- DO NOT EDIT BELOW (Derived Parameters) ---
NUM_VEHICLES_TO_USE = NUM_TRUCKS
NUM_TASKS_TO_USE = 1000