# HDT_Swapping_Optimization/src/common/config_final.py
import os

# --- 路径定义 ---
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RESULTS_DIR = os.path.join(PROJECT_ROOT, "results")
DATA_DIR = os.path.join(PROJECT_ROOT, "data", "raw")

# 确保results目录存在
os.makedirs(RESULTS_DIR, exist_ok=True)

# --- 文件名定义 ---
STATION_PARAMS_FILENAME = "副本2、能源站物理与服务参数-final.xlsx - Sheet1.csv"
ROAD_NETWORK_FILENAME = "副本4、路网与EV需求参数-final.xlsx - Sheet1.csv"
TASK_FLEET_FILENAME = "副本4、路网与EV需求参数-final.xlsx - 车队典型数据汇总.csv"
BATTERY_PARAMS_FILENAME = "副本1、HDT电池物理参数-final.xlsx - Sheet1.csv"
CHARGE_LOAD_FILENAME = "充电负荷报表-海宜路1、2号5月.csv"
BATTERY_SOC_FILENAME = "电池SOC数据.csv"

# --- 时间离散化 ---
TIME_HORIZON_HOURS = 24
TIME_STEP_MINUTES = 30
TOTAL_TIME_STEPS = int(TIME_HORIZON_HOURS * 60 / TIME_STEP_MINUTES)
TIME_STEP_HOURS = TIME_STEP_MINUTES / 60.0

# --- 经济与惩罚参数 ---
MANPOWER_COST_PER_HOUR = 150.0
DELAY_PENALTY_PER_HOUR = 500.0
FIXED_SWAP_COST = 50.0
EV_UNSERVED_PENALTY_PER_KWH = 10.0
GRID_PEAK_PRICE_PENALTY = 50.0
UNASSIGNED_TASK_PENALTY = 500000.0
AVG_TASKS_PER_TRUCK = 1 # 战术规划阶段的核心假设

# --- 电网物理参数 ---
BASE_VOLTAGE_KV = 10.0
BASE_POWER_MVA = 1.0
LINE_RESISTANCE_OHM_PER_KM = 0.16
LINE_REACTANCE_OHM_PER_KM = 0.12
MIN_VOLTAGE_PU = 0.95
MAX_VOLTAGE_PU = 1.05
LINE_THERMAL_LIMIT_MVA = 2.0

# --- 【关键修复】将所有HDT物理参数全部加回来 ---
LOADING_UNLOADING_TIME_HOURS = 0.5
SWAP_DURATION_HOURS = 0.25
HDT_BATTERY_CAPACITY_KWH = 350.0
HDT_MIN_SOC_KWH = HDT_BATTERY_CAPACITY_KWH * 0.15
HDT_EMPTY_WEIGHT_TON = 10.0
HDT_BASE_CONSUMPTION_KWH_PER_KM = 1.2
HDT_WEIGHT_CONSUMPTION_KWH_PER_KM_TON = 0.05

# --- 【关键修复】将所有EV和能源站参数全部加回来 ---
EV_AVG_CHARGE_DEMAND_KWH = 40.0
EV_MAX_CHARGE_POWER_KW = 60.0
BATTERY_CHARGE_EFFICIENCY = 0.95
BATTERY_DISCHARGE_EFFICIENCY = 0.95
BATTERY_MAX_CHARGE_POWER_KW = 120
STATION_MAX_GRID_POWER_KW = {'SwapStation1': 2000, 'SwapStation2': 1500, '换电站ID1': 2000, '换电站ID2': 1200, '换电站ID3': 2500, '换电站ID4': 1200}
PV_PEAK_POWER_KW = {'SwapStation1': 500, 'SwapStation2': 400, '换电站ID1': 300, '换电站ID2': 200, '换电站ID3': 400, '换电站ID4': 150}


# --- 求解器与模型 ---
SOLVER_NAME = 'ipopt'
TIME_LIMIT_SECONDS = 600
BIG_M = 10000